# Build settings

site.locale: "fr"
title: Thomas Vercier
name: Thomas Vercier
email: thomasvercier@gmail.com
description: "Site de Thomas Vercier."
logo: "/assets/images/moi.jpg"
include: ["_pages"]

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "aqua" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


author:
  name: "Thomas Vercier"
  avatar: "/assets/images/moi.jpg"
  location: "Martigues"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Thomas-Ver"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/thomas-vercier-b96030211/"
